.in
.decl Arc(x:integer, y:integer, l:integer)
.input Arc.csv

.out
.decl Zero(x:integer, y:integer)
.decl One(x:integer, y:integer)
.decl Dyck(x:integer, y:integer)


.rule
Zero(x, y) :- Arc(x, y, 0).
One(x, y) :- Arc(x, y, 1).

Dyck(x, y) :- Zero(x, z), Zero(z, y).
Dyck(x, y) :- One(x, z), One(z, y).
Dyck(x, y) :- Zero(x, z), Dyck(z, w), Zero(w, y).
Dyck(x, y) :- One(x, z), Dyck(z, w), One(w, y).
Dyck(x, y) :- Dyck(x, z), Dyck(z, y).
