[package]
name = "flowlog-parser"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Parser and typechecker for the FlowLog Datalog language."
readme = "README.md"
keywords = ["datalog", "parser", "typechecker", "compiler"]
categories = ["compilers", "parser-implementations", "database"]

[dependencies]
flowlog-common.workspace = true
flowlog-error.workspace = true

codespan-reporting.workspace = true
educe = { workspace = true }
litrs = { workspace = true }
ordered-float = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
rstest.workspace = true
tempfile.workspace = true

[lints]
workspace = true
