use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::parse2;

use parser::{DataType, Relation};

use super::Compiler;

impl Compiler {
    /// Render `src/relops.rs` for incremental mode.
    ///
    /// - Nullary relations handled by a dedicated generator (no parsing; worker0 only).
    /// - Non-nullary relations:
    ///   - No panics: parse/open errors print to stderr and skip.
    ///   - Shard by first column (int mod peers; string FNV-1a).
    ///   - Delimiter is `rel.input_delimiter()` (1 byte, default comma).
    pub(crate) fn render_relops(&self, edbs: Vec<&Relation>) -> String {
        let str_intern = self.imports.needs_string_intern();

        let needs_shard_str = edbs
            .iter()
            .any(|rel| rel.data_type().contains(&DataType::String));
        let needs_shard_int = edbs.iter().any(|rel| {
            rel.arity() > 0
                && matches!(
                    rel.data_type().first(),
                    Some(&DataType::Int8)
                        | Some(&DataType::Int16)
                        | Some(&DataType::Int32)
                        | Some(&DataType::Int64)
                        | Some(&DataType::UInt8)
                        | Some(&DataType::UInt16)
                        | Some(&DataType::UInt32)
                        | Some(&DataType::UInt64)
                        | Some(&DataType::Float32)
                        | Some(&DataType::Float64)
                        | Some(&DataType::Bool)
                )
        });

        let intern_import = if str_intern && needs_shard_str {
            quote! {
                use super::intern;
                use lasso::Spur;
            }
        } else {
            quote! {}
        };

        let rel_impls: Vec<TokenStream> = edbs
            .iter()
            .map(|rel| {
                if rel.arity() == 0 {
                    gen_one_rel_nullary(rel)
                } else {
                    gen_one_rel_nonnullary(rel, str_intern)
                }
            })
            .collect();

        // Shard functions: only emit each one when actually needed.
        let shard_int_fn = if needs_shard_int {
            quote! {
                /// Shard on an integer first column by `first % peers`.
                #[inline]
                fn shard_int(first: i64, peers: usize, index: usize) -> bool {
                    first.rem_euclid(peers as i64) as usize == index
                }
            }
        } else {
            quote! {}
        };

        let shard_string_fn = if needs_shard_str {
            if str_intern {
                quote! {
                    /// Shard on a `Spur` (interned string) first column by its inner key.
                    #[inline]
                    fn shard_spur(first: Spur, peers: usize, index: usize) -> bool {
                        (first.into_inner().get() as usize) % peers == index
                    }
                }
            } else {
                quote! {
                    /// Shard on a string first column using 32-bit FNV-1a.
                    #[inline]
                    fn shard_str(first: &str, peers: usize, index: usize) -> bool {
                        // 32-bit FNV-1a
                        let mut hash: u32 = 0x811c9dc5;
                        for &b in first.as_bytes() {
                            hash ^= b as u32;
                            hash = hash.wrapping_mul(0x01000193);
                        }
                        (hash as usize) % peers == index
                    }
                }
            }
        } else {
            quote! {}
        };

        let file = quote! {
            //! Dynamic relation handlers for incremental input sessions.
            //!
            //! This module is generated by the FlowLog compiler. It defines a uniform interface
            //! (`RelOps`) over per-relation input handlers backed by
            //! [`differential_dataflow::input::InputSession`].
            //!
            //! Each generated handler supports:
            //! - Applying a single tuple update (`apply_tuple`)
            //! - Applying updates from a delimited file (`apply_file`)
            //! - Advancing / flushing / closing the underlying input session
            //!
            //! Sharding:
            //! - For `apply_tuple`, updates are sharded by the *first* column
            //!   (integer mod peers; string FNV-1a or interned ID modulo).
            //! - For `apply_file`, byte-range parallel reading is used instead:
            //!   each worker reads only its ~1/N slice of the file.
            //!
            //! Nullary relations:
            //! - Are handled by a dedicated generator (no parsing).
            //! - Only worker 0 applies updates to avoid multiplying diffs across workers.
            //! - File ingestion is intentionally unsupported (tuple interaction only).

            use differential_dataflow::input::InputSession;

            use std::fs::File;
            use std::io::{BufRead, BufReader, Read, Seek, SeekFrom};
            use std::path::Path;
            use std::time::Instant;

            #intern_import

            /// Diff type used by incremental input sessions.
            type Diff = i32;

            /// Operations supported by a dynamic relation handler.
            ///
            /// Implementations are generated per EDB relation and backed by an
            /// [`InputSession`]. Implementations are expected to be robust:
            /// parsing and I/O errors should be reported to stderr and skipped.
            pub(crate) trait RelOps {
                /// Apply a single tuple update.
                ///
                /// `tuple` is a delimited string whose delimiter is relation-specific.
                /// Implementations should shard by the first column and apply the update
                /// only on the matching worker.
                fn apply_tuple(&mut self, tuple: &str, diff: Diff, peers: usize, index: usize);

                /// Apply updates from a file.
                ///
                /// Implementations use byte-range parallel reading: each worker reads
                /// only its ~1/N byte slice of the file, parsing and applying `diff`
                /// to each row within its range.
                fn apply_file(&mut self, path: &Path, diff: Diff, peers: usize, index: usize);

                /// Advance the input session to logical time `t`.
                fn advance_to(&mut self, t: u32);

                /// Flush buffered updates into the dataflow.
                fn flush(&mut self);

                /// Close the input session.
                fn close(&mut self);
            }

            #shard_int_fn
            #shard_string_fn

            /// Open a byte-range slice of a file for parallel reading.
            ///
            /// Each worker reads approximately `1/peers` of the file. Non-first workers
            /// skip the partial line at their seek offset so no line is double-read or missed.
            ///
            /// Returns `(reader, bytes_to_read)`.
            fn __byte_range_reader(
                path: &Path,
                index: usize,
                peers: usize,
            ) -> Option<(BufReader<File>, u64)> {
                let mut file = match File::open(path) {
                    Ok(f) => f,
                    Err(e) => {
                        eprintln!("[relops] failed to open {}: {}", path.display(), e);
                        return None;
                    }
                };
                let file_size = match file.metadata() {
                    Ok(m) => m.len(),
                    Err(e) => {
                        eprintln!("[relops] failed to get metadata for {}: {}", path.display(), e);
                        return None;
                    }
                };

                let chunk = file_size / peers as u64;
                let start = chunk * index as u64;
                let end = if index == peers - 1 {
                    file_size
                } else {
                    chunk * (index + 1) as u64
                };

                // Nothing to read for this worker.
                if start >= end {
                    return Some((BufReader::new(file), 0));
                }

                if index > 0 && start > 0 {
                    // Peek the byte before our range to see if we're on a line boundary.
                    if file.seek(SeekFrom::Start(start - 1)).is_err() {
                        return Some((BufReader::new(file), 0));
                    }
                    let mut reader = BufReader::new(file);
                    let mut peek = [0u8; 1];
                    if reader.read_exact(&mut peek).is_err() {
                        return Some((reader, 0));
                    }

                    if peek[0] == b'\n' {
                        // Exactly on a line boundary.
                        return Some((reader, end - start));
                    }
                    // Mid-line: skip the rest of this partial line.
                    let mut discard = Vec::new();
                    let skipped = reader.read_until(b'\n', &mut discard).unwrap_or(0);
                    return Some((reader, (end - start).saturating_sub(skipped as u64)));
                }

                // Worker 0: read from the beginning.
                Some((BufReader::new(file), end - start))
            }

            #(#rel_impls)*
        };

        let syntax = parse2(file).unwrap();
        prettyplease::unparse(&syntax)
    }
}

// ------------------------------------------------------------
// Per-relation generators
// ------------------------------------------------------------

fn gen_one_rel_nullary(rel: &Relation) -> TokenStream {
    let name = rel.name();
    let struct_name = format_ident!("Rel{}", name);

    quote! {
        /// Input handler for the nullary relation.
        ///
        /// Nullary relations store a single boolean-like fact (`True`/`False`) and are
        /// updated only by worker 0 to avoid multiplying diffs across workers.
        pub(crate) struct #struct_name {
            h: Option<InputSession<u32, (), Diff>>,
        }

        impl #struct_name {
            /// Create a new nullary handler.
            pub fn new(h: InputSession<u32, (), Diff>) -> Self {
                Self { h: Some(h) }
            }

            /// Borrow the underlying input session.
            #[inline]
            fn h_mut(&mut self) -> &mut InputSession<u32, (), Diff> {
                self.h.as_mut().unwrap()
            }
        }

        impl RelOps for #struct_name {
            fn apply_tuple(&mut self, tuple: &str, _diff: Diff, _peers: usize, index: usize) {
                // Nullary: only worker0 applies (avoid multiplying diffs across workers).
                if index != 0 { return; }

                let s = tuple.trim();
                let d: Diff = if s.eq_ignore_ascii_case("true") {
                    1
                } else if s.eq_ignore_ascii_case("false") {
                    -1
                } else {
                    eprintln!(
                        "[relops][{}] nullary expects tuple 'True' or 'False', got {:?}",
                        #name,
                        s
                    );
                    return;
                };

                self.h_mut().update((), d);
            }

            fn apply_file(&mut self, path: &Path, _diff: Diff, _peers: usize, index: usize) {
                if index != 0 { return; }

                // Per request: nullary relations only allow tuple interaction.
                eprintln!(
                    "[relops][{}] nullary relation does not support file ingestion. Use: put {} True|False",
                    #name,
                    path.display()
                );
            }

            fn advance_to(&mut self, t: u32) {
                self.h_mut().advance_to(t);
            }

            fn flush(&mut self) {
                self.h_mut().flush();
            }

            fn close(&mut self) {
                if let Some(h) = self.h.take() {
                    h.close();
                }
            }
        }
    }
}

fn gen_one_rel_nonnullary(rel: &Relation, string_intern: bool) -> TokenStream {
    let name = rel.name();
    let struct_name = format_ident!("Rel{}", name);

    let arity = rel.arity();
    debug_assert!(arity > 0);

    let dts = rel.data_type();

    let delim_byte: u8 = rel
        .input_delimiter()
        .as_bytes()
        .first()
        .copied()
        .unwrap_or(b',');

    // tuple type: (T0,), (T0,T1,...)
    let rust_tys: Vec<TokenStream> = dts.iter().map(|dt| dt_to_rust(dt, string_intern)).collect();
    let tuple_ty: TokenStream = match arity {
        1 => {
            let t0 = &rust_tys[0];
            quote! { (#t0,) }
        }
        _ => quote! { (#(#rust_tys),*) },
    };

    // shard decision (tuple path uses `return;`, file path uses `return None;`)
    let shard_tuple = match dts[0] {
        DataType::Int8 => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
        DataType::Int16 => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
        DataType::Int32 => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
        DataType::Int64 => quote! { if !shard_int(f0, peers, index) { return; } },
        DataType::UInt8 => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
        DataType::UInt16 => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
        DataType::UInt32 => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
        DataType::UInt64 => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
        DataType::Float32 => {
            quote! { if !shard_int(f0.into_inner().to_bits() as i64, peers, index) { return; } }
        }
        DataType::Float64 => {
            quote! { if !shard_int(f0.into_inner().to_bits() as i64, peers, index) { return; } }
        }
        DataType::String => {
            if string_intern {
                quote! { if !shard_spur(f0, peers, index) { return; } }
            } else {
                quote! { if !shard_str(f0.as_str(), peers, index) { return; } }
            }
        }
        DataType::Bool => quote! { if !shard_int(f0 as i64, peers, index) { return; } },
    };
    let tuple_parse_stmts = gen_parse_from_str(name, &dts, string_intern);
    let file_parse_stmts = gen_parse_from_bytes(name, &dts, string_intern);

    let update_expr = match arity {
        1 => quote! { (f0,) },
        _ => {
            let vars: Vec<_> = (0..arity).map(|i| format_ident!("f{i}")).collect();
            quote! { (#(#vars),*) }
        }
    };

    quote! {
        /// Input handler for the relation.
        ///
        /// - Parses tuples using the relation delimiter.
        /// - Shards updates by the first column across `peers`.
        /// - Reports parse / I/O errors to stderr and skips malformed rows.
        pub(crate) struct #struct_name {
            h: Option<InputSession<u32, #tuple_ty, Diff>>,
            /// Delimiter byte used for parsing tuple strings / file rows.
            delim: u8,
        }

        impl #struct_name {
            /// Create a new handler.
            pub fn new(h: InputSession<u32, #tuple_ty, Diff>) -> Self {
                Self { h: Some(h), delim: #delim_byte }
            }

            /// Borrow the underlying input session.
            #[inline]
            fn h_mut(&mut self) -> &mut InputSession<u32, #tuple_ty, Diff> {
                self.h.as_mut().unwrap()
            }
        }

        impl RelOps for #struct_name {
            fn apply_tuple(&mut self, tuple: &str, diff: Diff, peers: usize, index: usize) {
                let tuple = tuple.trim();
                let delim = self.delim as char;
                let mut it = tuple.split(delim).map(|s| s.trim());

                #tuple_parse_stmts

                #shard_tuple
                self.h_mut().update(#update_expr, diff);
            }

            fn apply_file(&mut self, path: &Path, diff: Diff, peers: usize, index: usize) {
                let load_start = Instant::now();
                let (mut reader, byte_budget) = match __byte_range_reader(path, index, peers) {
                    Some(r) => r,
                    None => return,
                };
                let delim = self.delim;

                let mut buf = Vec::with_capacity(256);
                let mut bytes_consumed: u64 = 0;
                while bytes_consumed < byte_budget {
                    buf.clear();
                    match reader.read_until(b'\n', &mut buf) {
                        Ok(0) => break,
                        Ok(_) => {}
                        Err(e) => {
                            eprintln!("[relops][{}] I/O error reading {}: {}", #name, path.display(), e);
                            break;
                        }
                    }
                    bytes_consumed += buf.len() as u64;

                    // Strip trailing newline / carriage return.
                    if buf.last() == Some(&b'\n') { buf.pop(); }
                    if buf.last() == Some(&b'\r') { buf.pop(); }

                    if buf.is_empty() { continue; }

                    let line = &buf;
                    let row = (|| -> Option<_> {
                        let mut cols = line.split(|&b| b == delim);
                        #file_parse_stmts
                        Some(#update_expr)
                    })();
                    if let Some(row) = row {
                        self.h_mut().update(row, diff);
                    }
                }
                if index == 0 {
                    println!("{:?}:\tData loaded for {}", load_start.elapsed(), #name);
                }
            }

            fn advance_to(&mut self, t: u32) {
                self.h_mut().advance_to(t);
            }

            fn flush(&mut self) {
                self.h_mut().flush();
            }

            fn close(&mut self) {
                if let Some(h) = self.h.take() {
                    h.close();
                }
            }
        }
    }
}

// ------------------------------------------------------------
// Type + parsing helpers (codegen helpers)
// ------------------------------------------------------------

fn dt_to_rust(dt: &DataType, string_intern: bool) -> TokenStream {
    match *dt {
        DataType::Int8 => quote! { i8 },
        DataType::Int16 => quote! { i16 },
        DataType::Int32 => quote! { i32 },
        DataType::Int64 => quote! { i64 },
        DataType::UInt8 => quote! { u8 },
        DataType::UInt16 => quote! { u16 },
        DataType::UInt32 => quote! { u32 },
        DataType::UInt64 => quote! { u64 },
        DataType::Float32 => quote! { OrderedFloat<f32> },
        DataType::Float64 => quote! { OrderedFloat<f64> },
        DataType::String => {
            if string_intern {
                quote! { Spur }
            } else {
                quote! { String }
            }
        }
        DataType::Bool => quote! { bool },
    }
}

/// Parse from `it: Iterator<Item=&str>` into f0..f{n-1}.
/// On error: eprintln + return;
fn gen_parse_from_str(rel: &str, dts: &[DataType], string_intern: bool) -> TokenStream {
    let mut stmts = Vec::<TokenStream>::new();

    for (i, dt) in dts.iter().enumerate() {
        let v = format_ident!("f{i}");
        let idx = i;

        let get = quote! {
            let s = match it.next() {
                Some(s) => s,
                None => {
                    eprintln!("[relops][{}] bad tuple '{}': missing col {}", #rel, tuple, #idx);
                    return;
                }
            };
        };

        let parse = match *dt {
            DataType::Int8 => quote! {
                #get
                let #v: i8 = match s.parse::<i8>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not i8: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::Int16 => quote! {
                #get
                let #v: i16 = match s.parse::<i16>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not i16: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::Int32 => quote! {
                #get
                let #v: i32 = match s.parse::<i32>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not i32: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::Int64 => quote! {
                #get
                let #v: i64 = match s.parse::<i64>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not i64: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::UInt8 => quote! {
                #get
                let #v: u8 = match s.parse::<u8>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not u8: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::UInt16 => quote! {
                #get
                let #v: u16 = match s.parse::<u16>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not u16: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::UInt32 => quote! {
                #get
                let #v: u32 = match s.parse::<u32>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not u32: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::UInt64 => quote! {
                #get
                let #v: u64 = match s.parse::<u64>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not u64: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::Float32 => quote! {
                #get
                let #v: OrderedFloat<f32> = match s.parse::<f32>() {
                    Ok(v) => OrderedFloat(v),
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not f32: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::Float64 => quote! {
                #get
                let #v: OrderedFloat<f64> = match s.parse::<f64>() {
                    Ok(v) => OrderedFloat(v),
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not f64: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
            DataType::String => {
                if string_intern {
                    quote! {
                        #get
                        let #v: Spur = intern(s);
                    }
                } else {
                    quote! {
                        #get
                        let #v: String = s.to_string();
                    }
                }
            }
            DataType::Bool => quote! {
                #get
                let #v: bool = match s.parse::<bool>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!("[relops][{}] bad tuple '{}': col {} not bool: '{}'", #rel, tuple, #idx, s);
                        return;
                    }
                };
            },
        };

        stmts.push(parse);
    }

    quote! { #(#stmts)* }
}

/// Parse from `cols: Iterator<Item=&[u8]>` into f0..f{n-1}.
/// This runs inside `filter_map(|line| { ... })`, so errors return None.
fn gen_parse_from_bytes(rel: &str, dts: &[DataType], string_intern: bool) -> TokenStream {
    let mut stmts = Vec::<TokenStream>::new();

    for (i, dt) in dts.iter().enumerate() {
        let v = format_ident!("f{i}");
        let idx = i;

        let get_raw = quote! {
            let raw = match cols.next() {
                Some(b) => b,
                None => {
                    eprintln!(
                        "[relops][{}] bad row in {}: '{:?}' (missing col {})",
                        #rel,
                        path.display(),
                        String::from_utf8_lossy(&line),
                        #idx
                    );
                    return None;
                }
            };
        };

        let parse = match *dt {
            DataType::Int8 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: i8 = match s.parse::<i8>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not i8: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::Int16 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: i16 = match s.parse::<i16>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not i16: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::Int32 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: i32 = match s.parse::<i32>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not i32: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::Int64 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: i64 = match s.parse::<i64>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not i64: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::UInt8 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: u8 = match s.parse::<u8>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not u8: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::UInt16 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: u16 = match s.parse::<u16>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not u16: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::UInt32 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: u32 = match s.parse::<u32>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not u32: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::UInt64 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: u64 = match s.parse::<u64>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not u64: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::Float32 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: OrderedFloat<f32> = match s.parse::<f32>() {
                    Ok(v) => OrderedFloat(v),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not f32: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::Float64 => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: OrderedFloat<f64> = match s.parse::<f64>() {
                    Ok(v) => OrderedFloat(v),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not f64: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
            DataType::String => {
                let field_stmt = if string_intern {
                    quote! { let #v: Spur = intern(s); }
                } else {
                    quote! { let #v: String = s.to_string(); }
                };
                quote! {
                    #get_raw
                    let s = match std::str::from_utf8(raw) {
                        Ok(s) => s.trim(),
                        Err(_) => {
                            eprintln!(
                                "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                                #rel,
                                path.display(),
                                String::from_utf8_lossy(&line),
                                #idx
                            );
                            return None;
                        }
                    };
                    #field_stmt
                }
            }
            DataType::Bool => quote! {
                #get_raw
                let s = match std::str::from_utf8(raw) {
                    Ok(s) => s.trim(),
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not utf8)",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx
                        );
                        return None;
                    }
                };
                let #v: bool = match s.parse::<bool>() {
                    Ok(v) => v,
                    Err(_) => {
                        eprintln!(
                            "[relops][{}] bad row in {}: '{:?}' (col {} not bool: '{}')",
                            #rel,
                            path.display(),
                            String::from_utf8_lossy(&line),
                            #idx,
                            s
                        );
                        return None;
                    }
                };
            },
        };

        stmts.push(parse);
    }

    quote! { #(#stmts)* }
}
