//! The epoch-broadcast choreography a compiled incremental program runs.
//!
//! One worker sits at the prompt and drives ([`drive`]); every other
//! worker follows ([`follow`]). Both answer for their own dataflow state
//! through one [`Event`] callback, so the program supplies what only it
//! knows (its input handles, its outputs) and the protocol decides when:
//! who waits at which barrier, what an epoch publishes, and how a quit
//! reaches every worker.
//!
//! [`SharedTxn`] is the rendezvous: a published [`TxnState`] snapshot
//! behind a lock, and the barrier the workers meet at.

use std::sync::Arc;
use std::sync::Barrier;
use std::sync::RwLock;
use std::time::Instant;

use crate::cmd;
use crate::cmd::Cmd;
use crate::cmd::TxnOp;

// =============================================================================
// Wire state
// =============================================================================

/// What workers should do when they observe a new published [`TxnState`].
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum TxnAction {
    /// No action (idle / cleared).
    #[default]
    None,
    /// Execute `pending`, then advance/flush once.
    Commit,
    /// Quit all workers.
    Quit,
}

/// The snapshot a driver publishes once per epoch; every worker clones it
/// and acts on its `action`.
///
/// [`SharedTxn`] owns the publishing for a compiled binary; a library-mode
/// engine (generated by `flowlog-build`) publishes one from its host
/// thread instead, which is what keeps the fields public.
#[derive(Clone, Debug, Default)]
pub struct TxnState {
    /// Broadcast indicator: incremented on each publish so workers can
    /// detect "new txn".
    pub epoch: u32,
    /// Broadcast indicator: what the workers should do for this epoch.
    pub action: TxnAction,
    /// Updates queued for the next commit.
    pub pending: Vec<TxnOp>,
}

impl TxnState {
    /// Freestanding Quit snapshot: no carried pending ops.
    #[must_use]
    pub fn as_quit_snapshot(next_epoch: u32) -> TxnState {
        TxnState {
            epoch: next_epoch,
            action: TxnAction::Quit,
            pending: Vec::new(),
        }
    }
}

// =============================================================================
// Event
// =============================================================================

/// One step of an epoch that only the program can perform, delivered to
/// the callback [`drive`] and [`follow`] share.
///
/// Per committed epoch every worker sees `Apply` then `Advance`, and the
/// driving worker alone sees `Merge` after them; a quit delivers one
/// `Close` everywhere. The protocol owns the order, so a callback only
/// answers the step it is handed.
///
/// The ops arrive owned: an epoch's are read once, by one callback, so
/// handing them over outright spares the generated arm a lifetime.
#[derive(Debug)]
pub enum Event {
    /// Apply each op to this worker's input handles.
    Apply(Vec<TxnOp>),
    /// Advance every input to `t`, run the dataflow to fixpoint, and
    /// flush this worker's output buffers.
    Advance(u32),
    /// Merge and write the outputs of the data at time `t`, which is one
    /// before what `Advance` carried: sealing time `t` means advancing
    /// past it. Driving worker only.
    Merge(u32),
    /// Close every input and drain the dataflow to `t`, which is the last
    /// time `Advance` named.
    Close(u32),
}

// =============================================================================
// SharedTxn
// =============================================================================

/// The rendezvous one program's workers coordinate through: the published
/// snapshot and the barrier, cloned into every worker.
#[derive(Clone)]
pub struct SharedTxn {
    state: Arc<RwLock<TxnState>>,
    barrier: Arc<Barrier>,
}

impl SharedTxn {
    /// A rendezvous for exactly `workers` participants, the driver among
    /// them. The count must match the workers actually running [`drive`]
    /// or [`follow`], or every barrier wait deadlocks.
    #[must_use]
    pub fn new(workers: usize) -> Self {
        Self {
            state: Arc::new(RwLock::new(TxnState::default())),
            barrier: Arc::new(Barrier::new(workers)),
        }
    }

    /// A rendezvous sized by the `-w <n>` / `-w=<n>` in `args`, defaulting
    /// to one worker: the same flag timely reads, so the barrier and the
    /// worker set agree.
    #[must_use]
    pub fn from_args(args: &[String]) -> Self {
        Self::new(workers_from_args(args))
    }

    /// Rendezvous every worker once.
    fn wait(&self) {
        self.barrier.wait();
    }

    /// Publish the next epoch. Only the driving side writes, so the epoch
    /// counter needs no ordering beyond the lock.
    fn publish(&self, action: TxnAction, pending: Vec<TxnOp>) {
        let mut state = self.state.write().expect("txn state poisoned");
        state.epoch += 1;
        state.action = action;
        state.pending = pending;
    }

    /// This worker's copy of the published snapshot.
    fn snapshot(&self) -> TxnState {
        self.state.read().expect("txn state poisoned").clone()
    }

    /// Retire the published epoch, so an idle prompt leaves nothing
    /// marked actionable behind it.
    fn clear(&self) {
        let mut state = self.state.write().expect("txn state poisoned");
        state.action = TxnAction::None;
        state.pending.clear();
    }
}

/// The `-w <n>` / `-w=<n>` worker count in `args`, `1` when absent,
/// malformed, or zero: timely defaults to one worker, and a barrier of
/// zero would wave every wait through.
fn workers_from_args(args: &[String]) -> usize {
    let mut args = args.iter();
    while let Some(arg) = args.next() {
        let count = match arg.strip_prefix("-w") {
            Some("") => args.next().map(String::as_str),
            Some(rest) => rest.strip_prefix('='),
            None => continue,
        };
        if let Some(count) = count.and_then(|c| c.parse::<usize>().ok()) {
            return count.max(1);
        }
    }
    1
}

// =============================================================================
// drive / follow
// =============================================================================

/// Run the preload epoch: the one commit-shaped epoch before [`drive`]
/// and [`follow`], whose ingest the program has already applied when it
/// calls this.
///
/// `t` is the time that ingest wrote at, zero for a fresh session. Every
/// worker calls this, with `merges` on exactly one; the epoch then
/// advances, merges, and rendezvouses like a committed one, so preload
/// work is metered and drained the same way.
pub fn preload_epoch(shared: &SharedTxn, merges: bool, t: u32, mut on: impl FnMut(Event)) {
    on(Event::Advance(t + 1));
    shared.wait();
    if merges {
        on(Event::Merge(t));
    }
    shared.wait();
}

/// Read commands and drive the workers sharing `shared`, until a quit.
///
/// `next_cmd` supplies one command per call, prompted with the current
/// time; `None` means nothing this time and it is asked again, which is
/// how an interrupted or unreadable line keeps the prompt alive. Staging
/// lives here: an op outside a transaction begins one, an abort discards
/// what was staged, and only a commit publishes. Every published epoch
/// delivers [`Event`]s to `on` in their documented order, with this side
/// alone receiving [`Event::Merge`].
///
/// `t` is the time preload left off at, and advances by one per commit.
///
/// # Panics
///
/// If a worker sharing `shared` panicked mid-epoch, poisoning the
/// snapshot lock.
pub fn drive(
    shared: &SharedTxn,
    mut t: u32,
    mut next_cmd: impl FnMut(u32) -> Option<Cmd>,
    mut on: impl FnMut(Event),
) {
    println!("FlowLog Incremental Interactive Shell, type 'help' for commands.");

    let mut pending: Vec<TxnOp> = Vec::new();
    let mut in_txn = false;

    loop {
        let Some(command) = next_cmd(t) else { continue };
        match command {
            Cmd::Help => println!("{}", cmd::help_text()),

            Cmd::Begin => {
                in_txn = true;
                pending.clear();
                println!("(txn begin)");
            }

            Cmd::Abort => {
                in_txn = false;
                pending.clear();
                println!("(txn aborted)");
            }

            Cmd::Stage(op) => {
                if !in_txn {
                    in_txn = true;
                    pending.clear();
                }
                let kind = match &op {
                    TxnOp::Put { .. } => "put",
                    TxnOp::File { .. } => "file",
                };
                pending.push(op);
                println!("(queued {kind})");
            }

            Cmd::Commit => {
                if !in_txn {
                    println!("(no active txn)");
                    continue;
                }
                let round = Instant::now();

                shared.publish(TxnAction::Commit, std::mem::take(&mut pending));
                shared.wait();

                // Apply the published snapshot rather than a local copy,
                // so this worker runs exactly what the others read.
                let snapshot = shared.snapshot();
                on(Event::Apply(snapshot.pending));
                on(Event::Advance(t + 1));
                shared.wait();

                on(Event::Merge(t));
                println!("{:?}:\tCommitted & executed", round.elapsed());
                in_txn = false;
                t += 1;
                shared.wait();

                // The followers are already blocked at the next epoch's
                // first barrier, so nothing reads this retired snapshot.
                shared.clear();
            }

            Cmd::Quit => {
                shared.publish(TxnAction::Quit, Vec::new());
                shared.wait();
                on(Event::Close(t));
                shared.wait();
                return;
            }
        }
    }
}

/// Follow the driver sharing `shared`, until it publishes a quit.
///
/// Each published epoch delivers [`Event`]s to `on` in their documented
/// order, minus [`Event::Merge`], which is the driving side's alone. `t`
/// is the time preload left off at, and advances by one per commit, in
/// lockstep with the driver's.
///
/// # Panics
///
/// If a worker sharing `shared` panicked mid-epoch, poisoning the
/// snapshot lock, or if a snapshot arrives out of order, which no
/// single-driver run can produce.
pub fn follow(shared: &SharedTxn, mut t: u32, mut on: impl FnMut(Event)) {
    let mut last_epoch = 0u32;
    loop {
        shared.wait();

        let snapshot = shared.snapshot();
        assert!(snapshot.epoch > last_epoch, "stale epoch observed");
        last_epoch = snapshot.epoch;

        match snapshot.action {
            TxnAction::Commit => {
                on(Event::Apply(snapshot.pending));
                on(Event::Advance(t + 1));
                t += 1;
                shared.wait();

                // The driver merges its outputs here.
                shared.wait();
            }

            TxnAction::Quit => {
                on(Event::Close(t));
                shared.wait();
                return;
            }

            TxnAction::None => {
                unreachable!("the driver only publishes Commit or Quit");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;
    use std::thread;

    use rstest::rstest;

    use super::*;

    /// An [`Event`] flattened for assertion, `Apply` keeping its ops.
    #[derive(Debug, PartialEq, Eq)]
    enum Seen {
        Apply(Vec<TxnOp>),
        Advance(u32),
        Merge(u32),
        Close(u32),
    }

    fn record(log: &mut Vec<Seen>) -> impl FnMut(Event) + '_ {
        |event| {
            log.push(match event {
                Event::Apply(ops) => Seen::Apply(ops),
                Event::Advance(t) => Seen::Advance(t),
                Event::Merge(t) => Seen::Merge(t),
                Event::Close(t) => Seen::Close(t),
            });
        }
    }

    fn put_op(rel: &str) -> TxnOp {
        TxnOp::Put {
            rel: rel.to_string(),
            tuple: "1,2".to_string(),
            diff: 1,
        }
    }

    fn put(rel: &str) -> Cmd {
        Cmd::Stage(put_op(rel))
    }

    /// Run `script` through [`drive`] on one thread and [`follow`] on
    /// `followers` others, from time `t`; each worker's event log, the
    /// driver's first.
    fn run(script: Vec<Option<Cmd>>, followers: usize, t: u32) -> Vec<Vec<Seen>> {
        let shared = SharedTxn::new(followers + 1);
        let mut logs: Vec<Vec<Seen>> = (0..=followers).map(|_| Vec::new()).collect();

        thread::scope(|scope| {
            let mut logs = logs.iter_mut();
            let driver_log = logs.next().expect("driver log");
            let shared_ref = &shared;
            scope.spawn(move || {
                // The script must outlast the run: exhausting it means the
                // test forgot to quit, and hanging at the prompt would
                // deadlock the barrier instead of failing.
                let mut script = script.into_iter();
                drive(
                    shared_ref,
                    t,
                    |_| script.next().expect("script ended without a quit"),
                    record(driver_log),
                );
            });
            for log in logs {
                scope.spawn(|| follow(shared_ref, t, record(log)));
            }
        });

        logs
    }

    /// The preload epoch seals its data time by advancing one past it,
    /// merges on exactly the one worker asked to, and releases them all
    /// for the loops that follow.
    #[test]
    fn a_preload_epoch_advances_everywhere_and_merges_once() {
        let shared = SharedTxn::new(2);
        let mut logs: Vec<Vec<Seen>> = (0..2).map(|_| Vec::new()).collect();

        thread::scope(|scope| {
            let mut logs = logs.iter_mut();
            let merger_log = logs.next().expect("merger log");
            let other_log = logs.next().expect("other log");
            let shared_ref = &shared;
            scope.spawn(move || preload_epoch(shared_ref, true, 0, record(merger_log)));
            scope.spawn(move || preload_epoch(shared_ref, false, 0, record(other_log)));
        });

        assert_eq!(logs[0], vec![Seen::Advance(1), Seen::Merge(0)]);
        assert_eq!(logs[1], vec![Seen::Advance(1)]);
    }

    /// The full order of one committed epoch: every worker applies the
    /// same published ops and advances, and only the driver merges.
    #[test]
    fn a_commit_applies_and_advances_everywhere_but_merges_on_the_driver() {
        let logs = run(
            vec![
                Some(put("edge")),
                Some(put("node")),
                Some(Cmd::Commit),
                Some(Cmd::Quit),
            ],
            2,
            0,
        );

        let applied = vec![put_op("edge"), put_op("node")];
        assert_eq!(
            logs[0],
            vec![
                Seen::Apply(applied.clone()),
                Seen::Advance(1),
                Seen::Merge(0),
                Seen::Close(1),
            ]
        );
        for follower in &logs[1..] {
            assert_eq!(
                *follower,
                vec![
                    Seen::Apply(applied.clone()),
                    Seen::Advance(1),
                    Seen::Close(1),
                ]
            );
        }
    }

    /// Each commit is its own epoch: the time advances by one per commit
    /// on every worker, from wherever preload left off.
    #[test]
    fn each_commit_advances_the_time_by_one_from_the_start() {
        let logs = run(
            vec![
                Some(put("a")),
                Some(Cmd::Commit),
                Some(put("b")),
                Some(Cmd::Commit),
                Some(Cmd::Quit),
            ],
            1,
            5,
        );

        for log in &logs {
            let advances: Vec<&Seen> = log
                .iter()
                .filter(|s| matches!(s, Seen::Advance(_)))
                .collect();
            assert_eq!(advances, vec![&Seen::Advance(6), &Seen::Advance(7)]);
        }
        assert!(logs[0].contains(&Seen::Close(7)));
    }

    /// An abort discards the staged ops, so the next commit publishes
    /// only what was staged after it.
    #[test]
    fn an_abort_discards_the_staged_ops() {
        let logs = run(
            vec![
                Some(put("dropped")),
                Some(Cmd::Abort),
                Some(put("kept")),
                Some(Cmd::Commit),
                Some(Cmd::Quit),
            ],
            1,
            0,
        );

        assert_eq!(logs[1][0], Seen::Apply(vec![put_op("kept")]));
    }

    /// An explicit `begin` restarts staging, so what an implicit
    /// transaction had queued is dropped rather than folded in.
    #[test]
    fn a_begin_clears_what_an_implicit_txn_staged() {
        let logs = run(
            vec![
                Some(put("dropped")),
                Some(Cmd::Begin),
                Some(put("kept")),
                Some(Cmd::Commit),
                Some(Cmd::Quit),
            ],
            1,
            0,
        );

        assert_eq!(logs[1][0], Seen::Apply(vec![put_op("kept")]));
    }

    /// A commit with nothing staged publishes nothing: no epoch, no
    /// events, and the followers never wake.
    #[test]
    fn a_commit_outside_a_txn_publishes_nothing() {
        let logs = run(vec![Some(Cmd::Commit), Some(Cmd::Quit)], 2, 0);

        for log in &logs {
            assert_eq!(*log, vec![Seen::Close(0)]);
        }
    }

    /// Ops keep the order they were queued in, `put` and `file` alike.
    #[test]
    fn ops_arrive_in_the_order_queued() {
        let file_op = TxnOp::File {
            rel: "edge".to_string(),
            path: PathBuf::from("edge.csv"),
            diff: -1,
        };
        let logs = run(
            vec![
                Some(put("edge")),
                Some(Cmd::Stage(file_op.clone())),
                Some(Cmd::Commit),
                Some(Cmd::Quit),
            ],
            1,
            0,
        );

        assert_eq!(logs[1][0], Seen::Apply(vec![put_op("edge"), file_op]));
    }

    /// A read that yields nothing (a blank line, an interrupt) reads
    /// again rather than ending the shell, and `help` stays local: no
    /// protocol traffic for either.
    #[test]
    fn blank_reads_and_help_publish_nothing() {
        let logs = run(vec![None, Some(Cmd::Help), None, Some(Cmd::Quit)], 1, 0);

        for log in &logs {
            assert_eq!(*log, vec![Seen::Close(0)]);
        }
    }

    /// The prompt is shown the advanced time, so `[t=..]` moves with the
    /// commits.
    #[test]
    fn the_prompt_sees_the_advanced_time() {
        let shared = SharedTxn::new(1);
        let mut times = Vec::new();
        let mut script = vec![Some(put("edge")), Some(Cmd::Commit), Some(Cmd::Quit)].into_iter();
        drive(
            &shared,
            0,
            |t| {
                times.push(t);
                script.next().expect("script ended without a quit")
            },
            |_| {},
        );
        assert_eq!(times, vec![0, 0, 1]);
    }

    /// The `-w` spellings timely accepts, and the shapes that fall back
    /// to one worker: absent, malformed, and zero.
    #[rstest]
    #[case(&[], 1)]
    #[case(&["-w", "4"], 4)]
    #[case(&["-w=3"], 3)]
    #[case(&["prog", "-w", "2", "rest"], 2)]
    #[case(&["-w", "x"], 1)]
    #[case(&["-w=x"], 1)]
    #[case(&["-w", "0"], 1)]
    #[case(&["-w"], 1)]
    fn worker_count_reads_every_dash_w_spelling(#[case] args: &[&str], #[case] expected: usize) {
        let args: Vec<String> = args.iter().map(ToString::to_string).collect();
        assert_eq!(workers_from_args(&args), expected);
    }
}
