name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build_and_test:
    runs-on: namespace-profile-flowlog

    steps:
      - uses: actions/checkout@v4
      - name: ⚙️ Install dependencies and clippy
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          rustup component add clippy
      - name: 🔨 Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: 📎 Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: 🧪 Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: 🏁 Run batch smoke test
        run: |
          bash tests/e2e/run.sh
          bash tools/check/batch.sh tools/config/config_integer.txt --compile-only --sip
          bash tools/check/batch.sh tools/config/config_str.txt --compile-only --sip --str-intern
          bash tools/check/batch.sh tools/config/config_ci.txt
